import requests, pytest, allure

@allure.title('Апи тесты')
@allure.story('Проверка статус кода')

@pytest.mark.parametrize('status_code, url, label', [
    (200, "https://t.me/Zel_Gavan_bot", ""),
    (200, "https://zelgavan.by/infrastructure", "Инфраструктура"),
    (200,"https://yandex.by/maps/org/zhk_zelenaya_gavan/130388263400/?ll=27.741332%2C53.891943&mode=search&sctx=ZAAAAAgBEAAaKAoSCXmu78NBjjtAES%2F6CtKM80pAEhIJODKP%2FMHA1T8RVHHjFvNzvz8iBgABAgMEBSgKOABAnQFIAWoCdWGdAc3MTD2gAQCoAQC9ASevfUjCAQbog%2Fzd5QPqAQDyAQD4AQCCAjHQt9C10LvQtdC90LDRjyDQs9Cw0LLQsNC90Ywg0L7RhNC40YEg0L%2FRgNC%2B0LTQsNC2igIAkgIAmgIMZGVza3RvcC1tYXBz&sll=27.741332%2C53.891943&sspn=0.021243%2C0.007681&text=%D0%B7%D0%B5%D0%BB%D0%B5%D0%BD%D0%B0%D1%8F%20%D0%B3%D0%B0%D0%B2%D0%B0%D0%BD%D1%8C%20%D0%BE%D1%84%D0%B8%D1%81%20%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%B6&z=16","Подробный маршрут"),
    (200, "https://zelgavan.by/immovables", "Недвижимость"),
    (200, "https://zelgavan.by/#", ""),
    (200, "https://tour.theviewvr.com/?locationId=3256", "3D тур"),
    (200, "https://zelgavan.by/usloviya-pokupki", "Способы покупки"),
    (200, "https://zelgavan.by/contacts", "Контакты"),
    (200, "https://zelgavan.by/news/s-chego-nachinaetsya-detstvo-otkrylsya-pervyj-detskij-sad-ptichij-dom", ""),
    (200, "https://zelgavan.by/news/start-prodazh-taunhausa-14-2", ""),
    (200, "https://zelgavan.by/news/start-prodazh-sitihausa-6-7", ""),
    (200, "https://zelgavan.by/news", "Все новости"),
    (200, "https://zelgavan.by/advantages/detskij-sad", ""),
    (200, "https://zelgavan.by/advantages/golf-polya-chempionskogo-klassa", ""),
    (200, "https://zelgavan.by/advantages/parking", ""),
    (200, "https://zelgavan.by/advantages/mesta-otdyha-i-zony-dlya-barbekyu", ""),
    (200, "https://zelgavan.by/realty-type/urbanhouses", ""),
    (200, "https://zelgavan.by/realty-type/urban-villa", ""),
    (200, "https://zelgavan.by/realty-type/linehouses", ""),
    (200, "https://zelgavan.by/realty-type/duplex", ""),
    (200, "https://zelgavan.by/realty-type/cottages", ""),
    (200, "https://zelgavan.by/realty-type/parkings-lots", ""),
    (200, "https://zelgavan.by/pages/usloviya-obrabotki", "условия обработки пе"),
    (200, "https://zelgavan.by/house-type/sitihaus-6-7", "Подробнее о доме"),
    (200, "https://zelgavan.by/stories/zelyonaya-gavan-netipichnaya-dlya-belarusi-kombinacziya-variantov-zhilya", "Читать полностью"),
    (200, "https://zelgavan.by/stories", "Больше историй"),
    (200, "https://zelgavan.by/pages/politika-obrabotki-fajlov-cookie", "Политики в отношении"),
    (200, "https://zelgavan.by/map", "Генплан"),
    (200, "https://zelgavan.by/news/marshrutnoe-taksi-v-zelenuyu-gavan", "Транспорт"),
    (200, "https://zelgavan.by/realty-search", "Выбор по параметрам"),
    (200, "https://zelgavan.by/pages/upravl-ya-yu-shh-a-ya-kompani-ya-a-100-komfort", "А-100 Комфорт"),
    (200, "https://zelgavan.by/about-developer", "О застройщике"),
    (200, "https://zelgavan.by/finishings/white-box", "White box"),
    (200, "https://zelgavan.by/finishings/nordic", "Nordic"),
    (200, "https://zelgavan.by/forms/care", "Служба заботы о клие"),
    (200, "https://zelgavan.by/realty-type/cityhouse", ""),
    (200, "https://zelgavan.by/harbor-excursion", "Экскурсия"),
    (200, "https://zelgavan.by/immovables/5-komnatnye", "5 комнат и более"),
    (200, "https://zelgavan.by/infrastructure", "Инфраструктура"),
    (200, "https://zelgavan.by/immovables", "Недвижимость"),
    (200, "https://zelgavan.by/immovables/2-komnatnye", "2-комнатные"),
    (200, "https://zelgavan.by/usloviya-pokupki", "Способы покупки"),
    (200, "https://zelgavan.by/#", ""),
    (200, "https://zelgavan.by/immovables/4-komnatnye", "4-комнатные"),
    (200, "https://zelgavan.by/contacts", "Контакты"),
    (200, "https://zelgavan.by/immovables/3-komnatnye", "3-комнатные"),
    (200, "https://zelgavan.by/news/s-chego-nachinaetsya-detstvo-otkrylsya-pervyj-detskij-sad-ptichij-dom", ""),
    (200, "https://zelgavan.by/news/start-prodazh-sitihausa-6-7", ""),
    (200, "https://zelgavan.by/advantages/detskij-sad", "Образование"),
    (200, "https://zelgavan.by/advantages/golf-polya-chempionskogo-klassa", "Гольф-клуб"),
    (200, "https://zelgavan.by/news/start-prodazh-taunhausa-14-2", ""),
    (200, "https://zelgavan.by/news", "Новости"),
    (200, "https://zelgavan.by/realty-type/duplex", "Дуплексы"),
    (200, "https://zelgavan.by/realty-type/urbanhouses", "Таунхаусы"),
    (200, "https://zelgavan.by/realty-type/linehouses", "Лайнхаусы"),
    (200, "https://zelgavan.by/realty-type/urban-villa", "Урбан-виллы"),
    (200, "https://zelgavan.by/stories", "Истории жителей"),
    (200, "https://zelgavan.by/pages/politika-obrabotki-fajlov-cookie", "здесь."),
    (200, "https://zelgavan.by/pages/usloviya-obrabotki", "условия обработки пе"),
    (200, "https://zelgavan.by/realty-type/parkings-lots", "Паркинги"),
    (200, "https://zelgavan.by/news/marshrutnoe-taksi-v-zelenuyu-gavan", "Транспорт"),
    (200, "https://zelgavan.by/realty-search", "Выбор по параметрам"),
    (200, "https://zelgavan.by/pages/upravl-ya-yu-shh-a-ya-kompani-ya-a-100-komfort", "А-100 Комфорт"),
    (200, "https://zelgavan.by/realty-type/cottages", "Коттеджи"),
    (200, "https://zelgavan.by/about-developer", "О застройщике"),
    (200, "https://zelgavan.by/finishings/white-box", "White box"),
    (200, "https://zelgavan.by/finishings/nordic", "Nordic"),
    (200, "https://zelgavan.by/harbor-excursion", "Экскурсия"),
    (200, "https://zelgavan.by/infrastructure", "Узнать больше"),
    (200, "https://zelgavan.by/usloviya-pokupki", "Способы покупки"),
    (200, "https://zelgavan.by/immovables", "Выбор по типам домов"),
    (200, "https://zelgavan.by/contacts", "Офис продаж"),
    (200, "https://zelgavan.by/advantages/detskij-sad", "Образование"),
    (200, "https://zelgavan.by/advantages/golf-polya-chempionskogo-klassa", "Гольф-клуб"),
    (200, "https://zelgavan.by/#", "Технические (обязате"),
    (200, "https://zelgavan.by/news", "Новости"),
    (200, "https://zelgavan.by/realty-type/duplex", "Дуплексы"),
    (200, "https://zelgavan.by/map", "Генплан"),
    (200, "https://zelgavan.by/realty-type/urbanhouses", "Таунхаусы"),
    (200, "https://zelgavan.by/realty-type/linehouses", "Лайнхаусы"),
    (200, "https://zelgavan.by/stories", "Истории жителей"),
    (200, "https://zelgavan.by/realty-type/cityhouse", "Ситихаусы"),
    (200, "https://zelgavan.by/pages/politika-obrabotki-fajlov-cookie", "здесь."),
    (200, "https://zelgavan.by/realty-type/urban-villa", "Урбан-виллы"),
    (200, "https://zelgavan.by/pages/usloviya-obrabotki", "условия обработки пе"),
    (200, "https://zelgavan.by/infrastructure", "Вся инфраструктура"),
    (200, "https://zelgavan.by/realty-type/parkings-lots", "Паркинги"),
    (200, "https://zelgavan.by/usloviya-pokupki", "Способы покупки"),
    (200, "https://zelgavan.by/contacts", "Контакты"),
    (200, "https://zelgavan.by/immovables", "Выбор по типам домов"),
    (200, "https://zelgavan.by/realty-type/cottages", "Коттеджи"),
    (200, "https://zelgavan.by/#", "Функциональные cooki"),
    (200, "https://zelgavan.by/pages/politika-obrabotki-fajlov-cookie", "здесь."),
    (200, "https://zelgavan.by/pages/usloviya-obrabotki", "условия обработки пе"),
    (200, "https://zelgavan.by/infrastructure", "Вся инфраструктура"),
    (200, "https://zelgavan.by/contacts", "Контакты"),
    (200, "https://zelgavan.by/pages/usloviya-obrabotki", "Политика конфиденциа"),
    (200, "https://zelgavan.by/#", "Аналитические/целевы"),
    (200, "https://zelgavan.by/#", ""),
    (200, "https://zelgavan.by/realty-type/cityhouse", "Ситихаусы"),
    (200, "https://zelgavan.by/map", "Смотреть генплан"),
    (200, "https://zelgavan.by/map", "Интерактивный план"),
    (200, "https://zelgavan.by/map", "Генплан"),
    (200, "https://zelgavan.by/popups/callback", "Записаться на консул"),
    (200, "https://zelgavan.by/popups/callback", "Онлайн-консультация"),
    (200, "https://zelgavan.by/construction-progress/", "Ход строительства"),
])

def test_api_status_code(status_code, url,label):
    with allure.step('Подготовка тестовых данных'):
        url = "https://zelgavan.by/"

        payload = {}
        headers = {
          'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
          'accept-language': 'en-US,en;q=0.9,ru;q=0.8',
          'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Mobile Safari/537.36',
          'Cookie': 'roistat_visit=2881243; roistat_first_visit=2881243; roistat_visit_cookie_expire=1209600; roistat_is_need_listen_requests=0; roistat_is_save_data_in_cookie=1; roistat_marker=google4_g_180943209589_759618475365_%D0%B7%D0%B5%D0%BB%D0%B5%D0%BD%D0%B0%D1%8F%20%D0%B3%D0%B0%D0%B2%D0%B0%D0%BD%D1%8C; roistat_marker_old=google4_g_180943209589_759618475365_%D0%B7%D0%B5%D0%BB%D0%B5%D0%BD%D0%B0%D1%8F%20%D0%B3%D0%B0%D0%B2%D0%B0%D0%BD%D1%8C; roistat_gclid=Cj0KCQjwsPzHBhDCARIsALlWNG2Pz6awsZbBVswripBUEMGWj3YpJO8lgViMSDkUooJG7L4Th9ozS94aAo6NEALw_wcB; _gcl_gs=2.1.k1$i1761589515$u186048162; _ga=GA1.1.172067973.1761589519; _gcl_au=1.1.1759978084.1761589519; _ym_uid=1761589519654701270; _ym_d=1761589519; _fbp=fb.1.1761589519440.732130255842181496; ___dc=b8f93ee4-207a-41e4-9eb7-2ae3bdf4fb2f; ACCEPT_COOKIES=1; ACCEPT_COOKIES_FUNC=1; ACCEPT_COOKIES_ANALIT=1; _tt_enable_cookie=1; _ttp=01K8KENWFKFDC5WW6QXFSHFP0Z_.tt.1; _gcl_aw=GCL.1761589766.Cj0KCQjwsPzHBhDCARIsALlWNG2Pz6awsZbBVswripBUEMGWj3YpJO8lgViMSDkUooJG7L4Th9ozS94aAo6NEALw_wcB; roistat_call_tracking=1; roistat_emailtracking_email=null; roistat_emailtracking_tracking_email=null; roistat_emailtracking_emails=null; zelgavan_ct_ref_c=https://zelgavan.by/; zelgavan_ct_id=33584884; zelgavan_ct_ref_l=https://zelgavan.by/; zelgavan_ct_s=eyJwaG9uZXMiOnsiKzM3NTI5MzAwMDAwMCI6IiszNzUyOTEwNTgzNzEiLCIrMzc1MjkzODA3MDkwIjoiKzM3NTI5MTA1ODM3MSJ9LCJyZWdleHAiOiIiLCJleHAiOiIyMDI1LTEwLTI5VDA3OjI4OjA3LjIyNloifQ==; zelgavan_ct_ga=1; zelgavan_ct_ya=1; zelgavan_ct_roi=1; zelgavan_ct_fb=1; zelgavan_ct_ga4_session=1; _ym_isad=2; _ym_visorc=w; XSRF-TOKEN=eyJpdiI6Im12OStSSVowdTBaVmk4SFBTamcyOXc9PSIsInZhbHVlIjoiQ1FDMVN1TU8rNkZCdG9kWmxxaGVZTlRLaEpCSkE0QlBBaEh6Z2pmUGpqS0FNZldTMnp1T2Q3bHErcVhWRG5qT29laHY2V1FLd0lsbzMyaEZvRHFNbytCV2NndlRDVFhWdHdTam9sY09Jc2xwS1FkVDNEeFQ3Q0NybFRkRTg3L3YiLCJtYWMiOiJjNjkxMjAxNjIyMTk5ZmFhOGM0OTZiZjEyMDVjYmY3YWMxZmRiNTdlOWIyMWViMmQ1NWI5YzI4YTViNmZhY2M0IiwidGFnIjoiIn0%3D; zelgavan_session=eyJpdiI6IlJjZlYyV2tmaWhMZndOck5KdFdqUVE9PSIsInZhbHVlIjoibjM3b3FiQXlDY2drZVNkTDgrSnBsNnRCSHkzZzlMTzMzUFBNbnJ4cVY3VmxDSW81UldpeFZQVXZkRWJCaU1SSjRlQkw4bEJtOVNsZWZDTXRQeXJuNHhHVDIxNE5EbjdXQXhsbUpYYjhIdnYwNFUxZU4vaXB1K01XaitDbHI0OCsiLCJtYWMiOiIxZjg1MzBmNDI1Mjc3Y2RiY2U1OTc3MmRlOTZkZmFhZWEwOTk0OWI3OTUwMzdlMjgyYWRmOWY2MzZkYjFhOGM0IiwidGFnIjoiIn0%3D; cookie=eyJpdiI6ImFJQ1ZjK3A0d2dIN2taUWNVbEtIdUE9PSIsInZhbHVlIjoiS1pqRzZuR09FaExIOG1FempUTzJQbXlWY3lIdmtXV1NTZmxjd29Ya2IzRTRSYXIydWJyZURQT1Jwd3dGaEcwYyIsIm1hYyI6IjZiYjhkZDYxMWNlYmFiZDZkZWVjYmRmMjMwMjBkYjY2ZDlkZDhjZDYxYTc5YzI4ZTc0YzM4MjkxMTIyNmIwMzkiLCJ0YWciOiIifQ%3D%3D; roistat_cookies_to_resave=roistat_ab%2Croistat_ab_submit; ttcsid=1761722527528::Y1CIdafIbtP3Mcvc44EV.2.1761722591351.0; ttcsid_CPK212RC77U6NIAFNGOG=1761722527528::CM5uQMVINofG--jUcNDW.2.1761722591351.0; _ga_CVJQ1803QP=GS2.1.s1761722527$o2$g1$t1761722635$j15$l0$h1914397806; XSRF-TOKEN=eyJpdiI6Ikd0RXp6aUFvbWtOS292MVpxanRnNWc9PSIsInZhbHVlIjoiR0hIRHlhZ0RpWEFDWG1pc3NUdUVkUzJFTDlrT21IL21tTkM4QVBoUGg4RVhndmVHdUphcUxXSERrQWNyZ2JJaVhxdlB3RE1jUjZVcEJzbTk1MjZKT3pjZFF1OGVXc2xTUndGRjY2d3lTK0hlQUwrMDNDUHk1ZWFSNU1wb2VkL3AiLCJtYWMiOiJkZTA0M2MyNzdkMzE3OWZkY2NiYWRiMmJlNGYyMGExYjI0ZTExOGY0OTdhNjM1NDM0YWUzMWFlYmRmMzMxMjlkIiwidGFnIjoiIn0%3D; cookie=eyJpdiI6IjRYdTk5cmlMZEJvTENVRnN2UXlKcEE9PSIsInZhbHVlIjoiUjEwcXhrVXNsNlNsNC9DNUljNnFmbUVYcVZiK1BoeTYwY3FIL0swSnFjVFdzTzlYMGo1REk3bVFKVldNRG41MyIsIm1hYyI6Ijg0N2JmZGE3ODVmODRlMGJmY2Q2OTZiYjVkY2M2ZmViOWJmMDg5YTZmMmJjZWJkZGJiN2E3YzVlYzRlODBjYjEiLCJ0YWciOiIifQ%3D%3D; zelgavan_session=eyJpdiI6Ik9HQm95ZUlWb2Z2QS9SY2NyNkdJR2c9PSIsInZhbHVlIjoiZXcyVEtCaDBFd0lpVmhoNUVoVWJ1V2UwbzlNM0xLaGdJRE5XMXA1ZkpUSFd3V3pncms0MlhVa3RrYWt6bVhMdVkzcDNrSWdZTWZqc1FkV01JbmFDVHpVU2ZIWm9jR3dQc2x1L2Z6VEpsOCtTcVkxbkNWUllMK1dPTkQrOXMzN0UiLCJtYWMiOiI1Y2M5OTNlYzllZTFkMzYzNDk5MGQ2Nzc0MmMxZWUxYTE2MjE1MTJhNzI0MDdlY2IwM2FhNWRiMGUzZGU1ZjJjIiwidGFnIjoiIn0%3D'
        }
    with allure.step(f'Вызов метода {url}'):
        response = requests.request("GET", url, headers=headers, data=payload)

    with allure.step('Проверка статус кода'):
        assert response.status_code == status_code, f'Статус кода {response.status_code}'
